# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('state',),
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('year_prod',)},
        ),
    ]
