# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20161108_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='theaters',
            field=models.ManyToManyField(to='films.Theater'),
        ),
            migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
