# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_theaters'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.Genre'),
            preserve_default=False,
        ),
    ]
